/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:22.1-60.10" *)
module Forwarding_unit(EX_MEM_RegWrite_i, EX_MEM_RD_i, ID_EX_RS_i, ID_EX_RT_i, MEM_WB_RegWrite_i, MEM_WB_RD_i, ForwardA_o, ForwardB_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:35.41-35.52" *)
  input [4:0] EX_MEM_RD_i;
  wire [4:0] EX_MEM_RD_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:34.13-34.30" *)
  input EX_MEM_RegWrite_i;
  wire EX_MEM_RegWrite_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:36.18-36.28" *)
  output [1:0] ForwardA_o;
  wire [1:0] ForwardA_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:36.30-36.40" *)
  output [1:0] ForwardB_o;
  wire [1:0] ForwardB_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:35.17-35.27" *)
  input [4:0] ID_EX_RS_i;
  wire [4:0] ID_EX_RS_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:35.29-35.39" *)
  input [4:0] ID_EX_RT_i;
  wire [4:0] ID_EX_RT_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:35.54-35.65" *)
  input [4:0] MEM_WB_RD_i;
  wire [4:0] MEM_WB_RD_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Forwarding_unit.v:34.32-34.49" *)
  input MEM_WB_RegWrite_i;
  wire MEM_WB_RegWrite_i;
  NOT _111_ (
    .A(EX_MEM_RD_i[4]),
    .Y(_040_)
  );
  NOT _112_ (
    .A(ID_EX_RS_i[4]),
    .Y(_041_)
  );
  NOT _113_ (
    .A(ID_EX_RT_i[4]),
    .Y(_042_)
  );
  NOT _114_ (
    .A(MEM_WB_RD_i[4]),
    .Y(_043_)
  );
  NOT _115_ (
    .A(MEM_WB_RegWrite_i),
    .Y(_044_)
  );
  NOR _116_ (
    .A(EX_MEM_RD_i[1]),
    .B(EX_MEM_RD_i[0]),
    .Y(_045_)
  );
  NOR _117_ (
    .A(EX_MEM_RD_i[3]),
    .B(EX_MEM_RD_i[2]),
    .Y(_046_)
  );
  NOT _118_ (
    .A(_046_),
    .Y(_047_)
  );
  NOR _119_ (
    .A(EX_MEM_RD_i[4]),
    .B(_047_),
    .Y(_048_)
  );
  NAND _120_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _121_ (
    .A(EX_MEM_RegWrite_i),
    .B(_049_),
    .Y(_050_)
  );
  NOR _122_ (
    .A(EX_MEM_RD_i[2]),
    .B(ID_EX_RS_i[2]),
    .Y(_051_)
  );
  NAND _123_ (
    .A(EX_MEM_RD_i[2]),
    .B(ID_EX_RS_i[2]),
    .Y(_052_)
  );
  NOT _124_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _125_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _126_ (
    .A(_040_),
    .B(ID_EX_RS_i[4]),
    .Y(_055_)
  );
  NOR _127_ (
    .A(EX_MEM_RD_i[4]),
    .B(_041_),
    .Y(_056_)
  );
  NOR _128_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _129_ (
    .A(EX_MEM_RD_i[0]),
    .B(ID_EX_RS_i[0]),
    .Y(_058_)
  );
  NOT _130_ (
    .A(_058_),
    .Y(_059_)
  );
  NAND _131_ (
    .A(EX_MEM_RD_i[0]),
    .B(ID_EX_RS_i[0]),
    .Y(_060_)
  );
  NAND _132_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _133_ (
    .A(_057_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _134_ (
    .A(_054_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _135_ (
    .A(EX_MEM_RD_i[1]),
    .B(ID_EX_RS_i[1]),
    .Y(_064_)
  );
  NAND _136_ (
    .A(EX_MEM_RD_i[1]),
    .B(ID_EX_RS_i[1]),
    .Y(_065_)
  );
  NOT _137_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _138_ (
    .A(_064_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _139_ (
    .A(EX_MEM_RD_i[3]),
    .B(ID_EX_RS_i[3]),
    .Y(_068_)
  );
  NAND _140_ (
    .A(EX_MEM_RD_i[3]),
    .B(ID_EX_RS_i[3]),
    .Y(_069_)
  );
  NOT _141_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR _142_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _143_ (
    .A(_067_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _144_ (
    .A(_063_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _145_ (
    .A(_050_),
    .B(_073_),
    .Y(ForwardA_o[1])
  );
  NOR _146_ (
    .A(EX_MEM_RD_i[2]),
    .B(ID_EX_RT_i[2]),
    .Y(_074_)
  );
  NAND _147_ (
    .A(EX_MEM_RD_i[2]),
    .B(ID_EX_RT_i[2]),
    .Y(_075_)
  );
  NOT _148_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _149_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _150_ (
    .A(_040_),
    .B(ID_EX_RT_i[4]),
    .Y(_078_)
  );
  NOR _151_ (
    .A(EX_MEM_RD_i[4]),
    .B(_042_),
    .Y(_079_)
  );
  NOR _152_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _153_ (
    .A(EX_MEM_RD_i[0]),
    .B(ID_EX_RT_i[0]),
    .Y(_081_)
  );
  NOT _154_ (
    .A(_081_),
    .Y(_082_)
  );
  NAND _155_ (
    .A(EX_MEM_RD_i[0]),
    .B(ID_EX_RT_i[0]),
    .Y(_083_)
  );
  NAND _156_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _157_ (
    .A(_080_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _158_ (
    .A(_077_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _159_ (
    .A(EX_MEM_RD_i[1]),
    .B(ID_EX_RT_i[1]),
    .Y(_087_)
  );
  NAND _160_ (
    .A(EX_MEM_RD_i[1]),
    .B(ID_EX_RT_i[1]),
    .Y(_088_)
  );
  NOT _161_ (
    .A(_088_),
    .Y(_089_)
  );
  NOR _162_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _163_ (
    .A(EX_MEM_RD_i[3]),
    .B(ID_EX_RT_i[3]),
    .Y(_091_)
  );
  NAND _164_ (
    .A(EX_MEM_RD_i[3]),
    .B(ID_EX_RT_i[3]),
    .Y(_092_)
  );
  NOT _165_ (
    .A(_092_),
    .Y(_093_)
  );
  NOR _166_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _167_ (
    .A(_090_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _168_ (
    .A(_086_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _169_ (
    .A(_050_),
    .B(_096_),
    .Y(ForwardB_o[1])
  );
  NOR _170_ (
    .A(MEM_WB_RD_i[1]),
    .B(MEM_WB_RD_i[0]),
    .Y(_097_)
  );
  NOT _171_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _172_ (
    .A(MEM_WB_RD_i[3]),
    .B(MEM_WB_RD_i[2]),
    .Y(_099_)
  );
  NAND _173_ (
    .A(_043_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _174_ (
    .A(_098_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _175_ (
    .A(_044_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _176_ (
    .A(ID_EX_RT_i[1]),
    .B(MEM_WB_RD_i[1]),
    .Y(_103_)
  );
  NOT _177_ (
    .A(_103_),
    .Y(_104_)
  );
  NAND _178_ (
    .A(ID_EX_RT_i[1]),
    .B(MEM_WB_RD_i[1]),
    .Y(_105_)
  );
  NAND _179_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _180_ (
    .A(ID_EX_RT_i[4]),
    .B(_043_),
    .Y(_107_)
  );
  NAND _181_ (
    .A(_042_),
    .B(MEM_WB_RD_i[4]),
    .Y(_108_)
  );
  NAND _182_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _183_ (
    .A(ID_EX_RT_i[3]),
    .B(MEM_WB_RD_i[3]),
    .Y(_110_)
  );
  NAND _184_ (
    .A(ID_EX_RT_i[3]),
    .B(MEM_WB_RD_i[3]),
    .Y(_000_)
  );
  NOT _185_ (
    .A(_000_),
    .Y(_001_)
  );
  NOR _186_ (
    .A(_110_),
    .B(_001_),
    .Y(_002_)
  );
  NOR _187_ (
    .A(_109_),
    .B(_002_),
    .Y(_003_)
  );
  NAND _188_ (
    .A(_106_),
    .B(_003_),
    .Y(_004_)
  );
  NOR _189_ (
    .A(ID_EX_RT_i[0]),
    .B(MEM_WB_RD_i[0]),
    .Y(_005_)
  );
  NOT _190_ (
    .A(_005_),
    .Y(_006_)
  );
  NAND _191_ (
    .A(ID_EX_RT_i[0]),
    .B(MEM_WB_RD_i[0]),
    .Y(_007_)
  );
  NAND _192_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _193_ (
    .A(ID_EX_RT_i[2]),
    .B(MEM_WB_RD_i[2]),
    .Y(_009_)
  );
  NOT _194_ (
    .A(_009_),
    .Y(_010_)
  );
  NAND _195_ (
    .A(ID_EX_RT_i[2]),
    .B(MEM_WB_RD_i[2]),
    .Y(_011_)
  );
  NAND _196_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _197_ (
    .A(_008_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _198_ (
    .A(_004_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _199_ (
    .A(_102_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _200_ (
    .A(ForwardB_o[1]),
    .B(_015_),
    .Y(ForwardB_o[0])
  );
  NOR _201_ (
    .A(ID_EX_RS_i[1]),
    .B(MEM_WB_RD_i[1]),
    .Y(_016_)
  );
  NOT _202_ (
    .A(_016_),
    .Y(_017_)
  );
  NAND _203_ (
    .A(ID_EX_RS_i[1]),
    .B(MEM_WB_RD_i[1]),
    .Y(_018_)
  );
  NAND _204_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _205_ (
    .A(ID_EX_RS_i[4]),
    .B(_043_),
    .Y(_020_)
  );
  NAND _206_ (
    .A(_041_),
    .B(MEM_WB_RD_i[4]),
    .Y(_021_)
  );
  NAND _207_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _208_ (
    .A(ID_EX_RS_i[3]),
    .B(MEM_WB_RD_i[3]),
    .Y(_023_)
  );
  NAND _209_ (
    .A(ID_EX_RS_i[3]),
    .B(MEM_WB_RD_i[3]),
    .Y(_024_)
  );
  NOT _210_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _211_ (
    .A(_023_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _212_ (
    .A(_022_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _213_ (
    .A(_019_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _214_ (
    .A(ID_EX_RS_i[0]),
    .B(MEM_WB_RD_i[0]),
    .Y(_029_)
  );
  NOT _215_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _216_ (
    .A(ID_EX_RS_i[0]),
    .B(MEM_WB_RD_i[0]),
    .Y(_031_)
  );
  NAND _217_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _218_ (
    .A(ID_EX_RS_i[2]),
    .B(MEM_WB_RD_i[2]),
    .Y(_033_)
  );
  NOT _219_ (
    .A(_033_),
    .Y(_034_)
  );
  NAND _220_ (
    .A(ID_EX_RS_i[2]),
    .B(MEM_WB_RD_i[2]),
    .Y(_035_)
  );
  NAND _221_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _222_ (
    .A(_032_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _223_ (
    .A(_028_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _224_ (
    .A(_102_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _225_ (
    .A(ForwardA_o[1]),
    .B(_039_),
    .Y(ForwardA_o[0])
  );
endmodule
