/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:23.1-37.10" *)
module Hazard_Detect(\IF_IDrs1_i[0] , \IF_IDrs1_i[1] , \IF_IDrs1_i[2] , \IF_IDrs1_i[3] , \IF_IDrs1_i[4] , \IF_IDrs2_i[0] , \IF_IDrs2_i[1] , \IF_IDrs2_i[2] , \IF_IDrs2_i[3] , \IF_IDrs2_i[4] , \ID_EXrd_i[0] , \ID_EXrd_i[1] , \ID_EXrd_i[2] , \ID_EXrd_i[3] , \ID_EXrd_i[4] , ID_EX_MemRead_i, Hazard_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:33.8-33.16" *)
  output Hazard_o;
  wire Hazard_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:31.7-31.22" *)
  input ID_EX_MemRead_i;
  wire ID_EX_MemRead_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.37-32.46" *)
  input \ID_EXrd_i[0] ;
  wire \ID_EXrd_i[0] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.37-32.46" *)
  input \ID_EXrd_i[1] ;
  wire \ID_EXrd_i[1] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.37-32.46" *)
  input \ID_EXrd_i[2] ;
  wire \ID_EXrd_i[2] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.37-32.46" *)
  input \ID_EXrd_i[3] ;
  wire \ID_EXrd_i[3] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.37-32.46" *)
  input \ID_EXrd_i[4] ;
  wire \ID_EXrd_i[4] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.13-32.23" *)
  input \IF_IDrs1_i[0] ;
  wire \IF_IDrs1_i[0] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.13-32.23" *)
  input \IF_IDrs1_i[1] ;
  wire \IF_IDrs1_i[1] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.13-32.23" *)
  input \IF_IDrs1_i[2] ;
  wire \IF_IDrs1_i[2] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.13-32.23" *)
  input \IF_IDrs1_i[3] ;
  wire \IF_IDrs1_i[3] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.13-32.23" *)
  input \IF_IDrs1_i[4] ;
  wire \IF_IDrs1_i[4] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.25-32.35" *)
  input \IF_IDrs2_i[0] ;
  wire \IF_IDrs2_i[0] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.25-32.35" *)
  input \IF_IDrs2_i[1] ;
  wire \IF_IDrs2_i[1] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.25-32.35" *)
  input \IF_IDrs2_i[2] ;
  wire \IF_IDrs2_i[2] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.25-32.35" *)
  input \IF_IDrs2_i[3] ;
  wire \IF_IDrs2_i[3] ;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\Hazard_Detect.v:32.25-32.35" *)
  input \IF_IDrs2_i[4] ;
  wire \IF_IDrs2_i[4] ;
  NOT _051_ (
    .A(\IF_IDrs1_i[0] ),
    .Y(_000_)
  );
  NOT _052_ (
    .A(\IF_IDrs1_i[1] ),
    .Y(_001_)
  );
  NOT _053_ (
    .A(\ID_EXrd_i[1] ),
    .Y(_002_)
  );
  NOT _054_ (
    .A(\ID_EXrd_i[2] ),
    .Y(_003_)
  );
  NOT _055_ (
    .A(\IF_IDrs1_i[3] ),
    .Y(_004_)
  );
  NOT _056_ (
    .A(\ID_EXrd_i[3] ),
    .Y(_005_)
  );
  NOT _057_ (
    .A(\IF_IDrs1_i[4] ),
    .Y(_006_)
  );
  NOT _058_ (
    .A(\ID_EXrd_i[4] ),
    .Y(_007_)
  );
  NOT _059_ (
    .A(\IF_IDrs2_i[0] ),
    .Y(_008_)
  );
  NOT _060_ (
    .A(\IF_IDrs2_i[1] ),
    .Y(_009_)
  );
  NOT _061_ (
    .A(\IF_IDrs2_i[4] ),
    .Y(_010_)
  );
  NOT _062_ (
    .A(ID_EX_MemRead_i),
    .Y(_011_)
  );
  NOR _063_ (
    .A(\ID_EXrd_i[1] ),
    .B(_009_),
    .Y(_012_)
  );
  NOR _064_ (
    .A(_002_),
    .B(\IF_IDrs2_i[1] ),
    .Y(_013_)
  );
  NOR _065_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _066_ (
    .A(\ID_EXrd_i[0] ),
    .B(_008_),
    .Y(_015_)
  );
  NOR _067_ (
    .A(_003_),
    .B(\IF_IDrs2_i[2] ),
    .Y(_016_)
  );
  NOR _068_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _069_ (
    .A(_014_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _070_ (
    .A(_005_),
    .B(\IF_IDrs2_i[3] ),
    .Y(_019_)
  );
  NOR _071_ (
    .A(\ID_EXrd_i[4] ),
    .B(_010_),
    .Y(_020_)
  );
  NOR _072_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _073_ (
    .A(\ID_EXrd_i[4] ),
    .B(_010_),
    .Y(_022_)
  );
  NAND _074_ (
    .A(_003_),
    .B(\IF_IDrs2_i[2] ),
    .Y(_023_)
  );
  NAND _075_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _076_ (
    .A(_005_),
    .B(\IF_IDrs2_i[3] ),
    .Y(_025_)
  );
  NAND _077_ (
    .A(\ID_EXrd_i[0] ),
    .B(_008_),
    .Y(_026_)
  );
  NAND _078_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _079_ (
    .A(_024_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _080_ (
    .A(_021_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _081_ (
    .A(_018_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _082_ (
    .A(\IF_IDrs1_i[1] ),
    .B(_002_),
    .Y(_031_)
  );
  NOR _083_ (
    .A(_001_),
    .B(\ID_EXrd_i[1] ),
    .Y(_032_)
  );
  NAND _084_ (
    .A(_000_),
    .B(\ID_EXrd_i[0] ),
    .Y(_033_)
  );
  NAND _085_ (
    .A(\IF_IDrs1_i[2] ),
    .B(_003_),
    .Y(_034_)
  );
  NAND _086_ (
    .A(\IF_IDrs1_i[4] ),
    .B(_007_),
    .Y(_035_)
  );
  NAND _087_ (
    .A(_006_),
    .B(\ID_EXrd_i[4] ),
    .Y(_036_)
  );
  NOR _088_ (
    .A(_004_),
    .B(\ID_EXrd_i[3] ),
    .Y(_037_)
  );
  NOR _089_ (
    .A(\IF_IDrs1_i[2] ),
    .B(_003_),
    .Y(_038_)
  );
  NOR _090_ (
    .A(_000_),
    .B(\ID_EXrd_i[0] ),
    .Y(_039_)
  );
  NOR _091_ (
    .A(\IF_IDrs1_i[3] ),
    .B(_005_),
    .Y(_040_)
  );
  NOR _092_ (
    .A(_037_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _093_ (
    .A(_032_),
    .B(_038_),
    .Y(_042_)
  );
  NAND _094_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _095_ (
    .A(_031_),
    .B(_039_),
    .Y(_044_)
  );
  NAND _096_ (
    .A(_034_),
    .B(_036_),
    .Y(_045_)
  );
  NAND _097_ (
    .A(_033_),
    .B(_035_),
    .Y(_046_)
  );
  NOR _098_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _099_ (
    .A(_044_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _100_ (
    .A(_043_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _101_ (
    .A(_030_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _102_ (
    .A(_011_),
    .B(_050_),
    .Y(Hazard_o)
  );
endmodule
