/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:23.1-84.10" *)
module MUX_Control(Hazard_i, RegDst_i, ALUOp_i, ALUSrc_i, RegWrite_i, MemToReg_i, MemRead_i, MemWrite_i, RegDst_o, ALUOp_o, ALUSrc_o, RegWrite_o, MemToReg_o, MemRead_o, MemWrite_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:41.13-41.20" *)
  input [1:0] ALUOp_i;
  wire [1:0] ALUOp_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:45.18-45.25" *)
  output [1:0] ALUOp_o;
  wire [1:0] ALUOp_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.17-43.25" *)
  input ALUSrc_i;
  wire ALUSrc_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:47.12-47.20" *)
  output ALUSrc_o;
  wire ALUSrc_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.7-43.15" *)
  input Hazard_i;
  wire Hazard_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.51-43.60" *)
  input MemRead_i;
  wire MemRead_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:47.46-47.55" *)
  output MemRead_o;
  wire MemRead_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.39-43.49" *)
  input MemToReg_i;
  wire MemToReg_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:47.34-47.44" *)
  output MemToReg_o;
  wire MemToReg_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.62-43.72" *)
  input MemWrite_i;
  wire MemWrite_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:47.57-47.67" *)
  output MemWrite_o;
  wire MemWrite_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:42.14-42.22" *)
  input [4:0] RegDst_i;
  wire [4:0] RegDst_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:46.19-46.27" *)
  output [4:0] RegDst_o;
  wire [4:0] RegDst_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:43.27-43.37" *)
  input RegWrite_i;
  wire RegWrite_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\MUX_Control.v:47.22-47.32" *)
  output RegWrite_o;
  wire RegWrite_o;
  NOT _12_ (
    .A(MemWrite_i),
    .Y(_00_)
  );
  NOT _13_ (
    .A(MemRead_i),
    .Y(_01_)
  );
  NOT _14_ (
    .A(MemToReg_i),
    .Y(_02_)
  );
  NOT _15_ (
    .A(RegWrite_i),
    .Y(_03_)
  );
  NOT _16_ (
    .A(ALUSrc_i),
    .Y(_04_)
  );
  NOT _17_ (
    .A(ALUOp_i[0]),
    .Y(_05_)
  );
  NOT _18_ (
    .A(ALUOp_i[1]),
    .Y(_06_)
  );
  NOT _19_ (
    .A(RegDst_i[0]),
    .Y(_07_)
  );
  NOT _20_ (
    .A(RegDst_i[1]),
    .Y(_08_)
  );
  NOT _21_ (
    .A(RegDst_i[2]),
    .Y(_09_)
  );
  NOT _22_ (
    .A(RegDst_i[3]),
    .Y(_10_)
  );
  NOT _23_ (
    .A(RegDst_i[4]),
    .Y(_11_)
  );
  NOR _24_ (
    .A(_00_),
    .B(Hazard_i),
    .Y(MemWrite_o)
  );
  NOR _25_ (
    .A(Hazard_i),
    .B(_01_),
    .Y(MemRead_o)
  );
  NOR _26_ (
    .A(Hazard_i),
    .B(_02_),
    .Y(MemToReg_o)
  );
  NOR _27_ (
    .A(Hazard_i),
    .B(_03_),
    .Y(RegWrite_o)
  );
  NOR _28_ (
    .A(Hazard_i),
    .B(_04_),
    .Y(ALUSrc_o)
  );
  NOR _29_ (
    .A(Hazard_i),
    .B(_05_),
    .Y(ALUOp_o[0])
  );
  NOR _30_ (
    .A(Hazard_i),
    .B(_06_),
    .Y(ALUOp_o[1])
  );
  NOR _31_ (
    .A(Hazard_i),
    .B(_07_),
    .Y(RegDst_o[0])
  );
  NOR _32_ (
    .A(Hazard_i),
    .B(_08_),
    .Y(RegDst_o[1])
  );
  NOR _33_ (
    .A(Hazard_i),
    .B(_09_),
    .Y(RegDst_o[2])
  );
  NOR _34_ (
    .A(Hazard_i),
    .B(_10_),
    .Y(RegDst_o[3])
  );
  NOR _35_ (
    .A(Hazard_i),
    .B(_11_),
    .Y(RegDst_o[4])
  );
endmodule
