/* Generated by Yosys 0.33+6 (git sha1 31ee566ec, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

(* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:22.1-60.10" *)
module PC(clk_i, start_i, pc_i, hazardpc_i, pc_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:32.21-32.26" *)
  input clk_i;
  wire clk_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:39.9-39.13" *)
  wire flag;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:33.30-33.40" *)
  input hazardpc_i;
  wire hazardpc_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:34.21-34.25" *)
  input [31:0] pc_i;
  wire [31:0] pc_i;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:35.21-35.25" *)
  output [31:0] pc_o;
  wire [31:0] pc_o;
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:33.21-33.28" *)
  input start_i;
  wire start_i;
  NOT _232_ (
    .A(flag),
    .Y(_066_)
  );
  NOT _233_ (
    .A(pc_i[1]),
    .Y(_067_)
  );
  NOT _234_ (
    .A(pc_i[0]),
    .Y(_068_)
  );
  NOT _235_ (
    .A(pc_i[2]),
    .Y(_069_)
  );
  NOT _236_ (
    .A(pc_i[9]),
    .Y(_070_)
  );
  NOT _237_ (
    .A(pc_i[8]),
    .Y(_071_)
  );
  NOT _238_ (
    .A(pc_i[11]),
    .Y(_072_)
  );
  NOT _239_ (
    .A(pc_i[10]),
    .Y(_073_)
  );
  NOT _240_ (
    .A(pc_i[13]),
    .Y(_074_)
  );
  NOT _241_ (
    .A(pc_i[12]),
    .Y(_075_)
  );
  NOT _242_ (
    .A(pc_i[15]),
    .Y(_076_)
  );
  NOT _243_ (
    .A(pc_i[14]),
    .Y(_077_)
  );
  NOT _244_ (
    .A(pc_i[17]),
    .Y(_078_)
  );
  NOT _245_ (
    .A(pc_i[16]),
    .Y(_079_)
  );
  NOT _246_ (
    .A(pc_i[19]),
    .Y(_080_)
  );
  NOT _247_ (
    .A(pc_i[18]),
    .Y(_081_)
  );
  NOT _248_ (
    .A(pc_i[21]),
    .Y(_082_)
  );
  NOT _249_ (
    .A(pc_i[20]),
    .Y(_083_)
  );
  NOT _250_ (
    .A(pc_i[23]),
    .Y(_084_)
  );
  NOT _251_ (
    .A(pc_i[22]),
    .Y(_085_)
  );
  NOT _252_ (
    .A(pc_i[25]),
    .Y(_086_)
  );
  NOT _253_ (
    .A(pc_i[24]),
    .Y(_087_)
  );
  NOT _254_ (
    .A(pc_i[27]),
    .Y(_088_)
  );
  NOT _255_ (
    .A(pc_i[26]),
    .Y(_089_)
  );
  NOT _256_ (
    .A(pc_i[29]),
    .Y(_090_)
  );
  NOT _257_ (
    .A(pc_i[28]),
    .Y(_091_)
  );
  NOT _258_ (
    .A(pc_i[31]),
    .Y(_092_)
  );
  NOT _259_ (
    .A(pc_i[30]),
    .Y(_093_)
  );
  NOT _260_ (
    .A(start_i),
    .Y(_000_)
  );
  NOT _261_ (
    .A(hazardpc_i),
    .Y(_094_)
  );
  NOR _262_ (
    .A(_000_),
    .B(hazardpc_i),
    .Y(_095_)
  );
  NAND _263_ (
    .A(start_i),
    .B(_094_),
    .Y(_096_)
  );
  NAND _264_ (
    .A(pc_o[31]),
    .B(_096_),
    .Y(_097_)
  );
  NOR _265_ (
    .A(flag),
    .B(_092_),
    .Y(_098_)
  );
  NAND _266_ (
    .A(_095_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _267_ (
    .A(_097_),
    .B(_099_),
    .Y(_065_)
  );
  NAND _268_ (
    .A(pc_o[30]),
    .B(_096_),
    .Y(_100_)
  );
  NOR _269_ (
    .A(flag),
    .B(_093_),
    .Y(_101_)
  );
  NAND _270_ (
    .A(_095_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _271_ (
    .A(_100_),
    .B(_102_),
    .Y(_064_)
  );
  NAND _272_ (
    .A(pc_o[29]),
    .B(_096_),
    .Y(_103_)
  );
  NOR _273_ (
    .A(flag),
    .B(_090_),
    .Y(_104_)
  );
  NAND _274_ (
    .A(_095_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _275_ (
    .A(_103_),
    .B(_105_),
    .Y(_063_)
  );
  NAND _276_ (
    .A(pc_o[28]),
    .B(_096_),
    .Y(_106_)
  );
  NOR _277_ (
    .A(flag),
    .B(_091_),
    .Y(_107_)
  );
  NAND _278_ (
    .A(_095_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _279_ (
    .A(_106_),
    .B(_108_),
    .Y(_062_)
  );
  NAND _280_ (
    .A(pc_o[27]),
    .B(_096_),
    .Y(_109_)
  );
  NOR _281_ (
    .A(flag),
    .B(_088_),
    .Y(_110_)
  );
  NAND _282_ (
    .A(_095_),
    .B(_110_),
    .Y(_111_)
  );
  NAND _283_ (
    .A(_109_),
    .B(_111_),
    .Y(_061_)
  );
  NAND _284_ (
    .A(pc_o[26]),
    .B(_096_),
    .Y(_112_)
  );
  NOR _285_ (
    .A(flag),
    .B(_089_),
    .Y(_113_)
  );
  NAND _286_ (
    .A(_095_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _287_ (
    .A(_112_),
    .B(_114_),
    .Y(_060_)
  );
  NAND _288_ (
    .A(pc_o[25]),
    .B(_096_),
    .Y(_115_)
  );
  NOR _289_ (
    .A(flag),
    .B(_086_),
    .Y(_116_)
  );
  NAND _290_ (
    .A(_095_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _291_ (
    .A(_115_),
    .B(_117_),
    .Y(_059_)
  );
  NAND _292_ (
    .A(pc_o[24]),
    .B(_096_),
    .Y(_118_)
  );
  NOR _293_ (
    .A(flag),
    .B(_087_),
    .Y(_119_)
  );
  NAND _294_ (
    .A(_095_),
    .B(_119_),
    .Y(_120_)
  );
  NAND _295_ (
    .A(_118_),
    .B(_120_),
    .Y(_058_)
  );
  NAND _296_ (
    .A(pc_o[23]),
    .B(_096_),
    .Y(_121_)
  );
  NOR _297_ (
    .A(flag),
    .B(_084_),
    .Y(_122_)
  );
  NAND _298_ (
    .A(_095_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _299_ (
    .A(_121_),
    .B(_123_),
    .Y(_057_)
  );
  NAND _300_ (
    .A(pc_o[22]),
    .B(_096_),
    .Y(_124_)
  );
  NOR _301_ (
    .A(flag),
    .B(_085_),
    .Y(_125_)
  );
  NAND _302_ (
    .A(_095_),
    .B(_125_),
    .Y(_126_)
  );
  NAND _303_ (
    .A(_124_),
    .B(_126_),
    .Y(_056_)
  );
  NAND _304_ (
    .A(pc_o[21]),
    .B(_096_),
    .Y(_127_)
  );
  NOR _305_ (
    .A(flag),
    .B(_082_),
    .Y(_128_)
  );
  NAND _306_ (
    .A(_095_),
    .B(_128_),
    .Y(_129_)
  );
  NAND _307_ (
    .A(_127_),
    .B(_129_),
    .Y(_055_)
  );
  NAND _308_ (
    .A(pc_o[20]),
    .B(_096_),
    .Y(_130_)
  );
  NOR _309_ (
    .A(flag),
    .B(_083_),
    .Y(_131_)
  );
  NAND _310_ (
    .A(_095_),
    .B(_131_),
    .Y(_132_)
  );
  NAND _311_ (
    .A(_130_),
    .B(_132_),
    .Y(_054_)
  );
  NAND _312_ (
    .A(pc_o[19]),
    .B(_096_),
    .Y(_133_)
  );
  NOR _313_ (
    .A(flag),
    .B(_080_),
    .Y(_134_)
  );
  NAND _314_ (
    .A(_095_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _315_ (
    .A(_133_),
    .B(_135_),
    .Y(_053_)
  );
  NAND _316_ (
    .A(pc_o[18]),
    .B(_096_),
    .Y(_136_)
  );
  NOR _317_ (
    .A(flag),
    .B(_081_),
    .Y(_137_)
  );
  NAND _318_ (
    .A(_095_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _319_ (
    .A(_136_),
    .B(_138_),
    .Y(_052_)
  );
  NAND _320_ (
    .A(pc_o[17]),
    .B(_096_),
    .Y(_139_)
  );
  NOR _321_ (
    .A(flag),
    .B(_078_),
    .Y(_140_)
  );
  NAND _322_ (
    .A(_095_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _323_ (
    .A(_139_),
    .B(_141_),
    .Y(_051_)
  );
  NAND _324_ (
    .A(pc_o[16]),
    .B(_096_),
    .Y(_142_)
  );
  NOR _325_ (
    .A(flag),
    .B(_079_),
    .Y(_143_)
  );
  NAND _326_ (
    .A(_095_),
    .B(_143_),
    .Y(_144_)
  );
  NAND _327_ (
    .A(_142_),
    .B(_144_),
    .Y(_050_)
  );
  NAND _328_ (
    .A(pc_o[15]),
    .B(_096_),
    .Y(_145_)
  );
  NOR _329_ (
    .A(flag),
    .B(_076_),
    .Y(_146_)
  );
  NAND _330_ (
    .A(_095_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _331_ (
    .A(_145_),
    .B(_147_),
    .Y(_049_)
  );
  NAND _332_ (
    .A(pc_o[14]),
    .B(_096_),
    .Y(_148_)
  );
  NOR _333_ (
    .A(flag),
    .B(_077_),
    .Y(_149_)
  );
  NAND _334_ (
    .A(_095_),
    .B(_149_),
    .Y(_150_)
  );
  NAND _335_ (
    .A(_148_),
    .B(_150_),
    .Y(_048_)
  );
  NAND _336_ (
    .A(pc_o[13]),
    .B(_096_),
    .Y(_151_)
  );
  NOR _337_ (
    .A(flag),
    .B(_074_),
    .Y(_152_)
  );
  NAND _338_ (
    .A(_095_),
    .B(_152_),
    .Y(_153_)
  );
  NAND _339_ (
    .A(_151_),
    .B(_153_),
    .Y(_047_)
  );
  NAND _340_ (
    .A(pc_o[12]),
    .B(_096_),
    .Y(_154_)
  );
  NOR _341_ (
    .A(flag),
    .B(_075_),
    .Y(_155_)
  );
  NAND _342_ (
    .A(_095_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _343_ (
    .A(_154_),
    .B(_156_),
    .Y(_046_)
  );
  NAND _344_ (
    .A(pc_o[11]),
    .B(_096_),
    .Y(_157_)
  );
  NOR _345_ (
    .A(flag),
    .B(_072_),
    .Y(_158_)
  );
  NAND _346_ (
    .A(_095_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _347_ (
    .A(_157_),
    .B(_159_),
    .Y(_045_)
  );
  NAND _348_ (
    .A(pc_o[10]),
    .B(_096_),
    .Y(_160_)
  );
  NOR _349_ (
    .A(flag),
    .B(_073_),
    .Y(_161_)
  );
  NAND _350_ (
    .A(_095_),
    .B(_161_),
    .Y(_162_)
  );
  NAND _351_ (
    .A(_160_),
    .B(_162_),
    .Y(_044_)
  );
  NAND _352_ (
    .A(pc_o[9]),
    .B(_096_),
    .Y(_163_)
  );
  NOR _353_ (
    .A(flag),
    .B(_070_),
    .Y(_164_)
  );
  NAND _354_ (
    .A(_095_),
    .B(_164_),
    .Y(_165_)
  );
  NAND _355_ (
    .A(_163_),
    .B(_165_),
    .Y(_043_)
  );
  NAND _356_ (
    .A(pc_o[8]),
    .B(_096_),
    .Y(_166_)
  );
  NOR _357_ (
    .A(flag),
    .B(_071_),
    .Y(_167_)
  );
  NAND _358_ (
    .A(_095_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _359_ (
    .A(_166_),
    .B(_168_),
    .Y(_042_)
  );
  NOR _360_ (
    .A(flag),
    .B(pc_i[7]),
    .Y(_169_)
  );
  NOT _361_ (
    .A(_169_),
    .Y(_170_)
  );
  NAND _362_ (
    .A(_095_),
    .B(_170_),
    .Y(_171_)
  );
  NAND _363_ (
    .A(pc_o[7]),
    .B(_096_),
    .Y(_172_)
  );
  NAND _364_ (
    .A(_171_),
    .B(_172_),
    .Y(_041_)
  );
  NOR _365_ (
    .A(flag),
    .B(pc_i[6]),
    .Y(_173_)
  );
  NOT _366_ (
    .A(_173_),
    .Y(_174_)
  );
  NAND _367_ (
    .A(_095_),
    .B(_174_),
    .Y(_175_)
  );
  NAND _368_ (
    .A(pc_o[6]),
    .B(_096_),
    .Y(_176_)
  );
  NAND _369_ (
    .A(_175_),
    .B(_176_),
    .Y(_040_)
  );
  NOR _370_ (
    .A(flag),
    .B(pc_i[5]),
    .Y(_177_)
  );
  NOT _371_ (
    .A(_177_),
    .Y(_178_)
  );
  NAND _372_ (
    .A(_095_),
    .B(_178_),
    .Y(_179_)
  );
  NAND _373_ (
    .A(pc_o[5]),
    .B(_096_),
    .Y(_180_)
  );
  NAND _374_ (
    .A(_179_),
    .B(_180_),
    .Y(_039_)
  );
  NOR _375_ (
    .A(flag),
    .B(pc_i[4]),
    .Y(_181_)
  );
  NOT _376_ (
    .A(_181_),
    .Y(_182_)
  );
  NAND _377_ (
    .A(_095_),
    .B(_182_),
    .Y(_183_)
  );
  NAND _378_ (
    .A(pc_o[4]),
    .B(_096_),
    .Y(_184_)
  );
  NAND _379_ (
    .A(_183_),
    .B(_184_),
    .Y(_038_)
  );
  NOR _380_ (
    .A(flag),
    .B(pc_i[3]),
    .Y(_185_)
  );
  NOT _381_ (
    .A(_185_),
    .Y(_186_)
  );
  NAND _382_ (
    .A(_095_),
    .B(_186_),
    .Y(_187_)
  );
  NAND _383_ (
    .A(pc_o[3]),
    .B(_096_),
    .Y(_188_)
  );
  NAND _384_ (
    .A(_187_),
    .B(_188_),
    .Y(_037_)
  );
  NAND _385_ (
    .A(pc_o[2]),
    .B(_096_),
    .Y(_189_)
  );
  NOR _386_ (
    .A(flag),
    .B(_069_),
    .Y(_190_)
  );
  NAND _387_ (
    .A(_095_),
    .B(_190_),
    .Y(_191_)
  );
  NAND _388_ (
    .A(_189_),
    .B(_191_),
    .Y(_036_)
  );
  NAND _389_ (
    .A(pc_o[1]),
    .B(_096_),
    .Y(_192_)
  );
  NOR _390_ (
    .A(flag),
    .B(_067_),
    .Y(_193_)
  );
  NAND _391_ (
    .A(_095_),
    .B(_193_),
    .Y(_194_)
  );
  NAND _392_ (
    .A(_192_),
    .B(_194_),
    .Y(_035_)
  );
  NAND _393_ (
    .A(pc_o[0]),
    .B(_096_),
    .Y(_195_)
  );
  NOR _394_ (
    .A(flag),
    .B(_068_),
    .Y(_196_)
  );
  NAND _395_ (
    .A(_095_),
    .B(_196_),
    .Y(_197_)
  );
  NAND _396_ (
    .A(_195_),
    .B(_197_),
    .Y(_034_)
  );
  NOR _397_ (
    .A(pc_i[21]),
    .B(pc_i[20]),
    .Y(_198_)
  );
  NOR _398_ (
    .A(pc_i[23]),
    .B(pc_i[22]),
    .Y(_199_)
  );
  NAND _399_ (
    .A(_198_),
    .B(_199_),
    .Y(_200_)
  );
  NOR _400_ (
    .A(pc_i[19]),
    .B(pc_i[18]),
    .Y(_201_)
  );
  NOR _401_ (
    .A(pc_i[17]),
    .B(pc_i[16]),
    .Y(_202_)
  );
  NAND _402_ (
    .A(_201_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _403_ (
    .A(_200_),
    .B(_203_),
    .Y(_204_)
  );
  NOR _404_ (
    .A(pc_i[31]),
    .B(pc_i[30]),
    .Y(_205_)
  );
  NOR _405_ (
    .A(pc_i[29]),
    .B(pc_i[28]),
    .Y(_206_)
  );
  NAND _406_ (
    .A(_205_),
    .B(_206_),
    .Y(_207_)
  );
  NOR _407_ (
    .A(pc_i[25]),
    .B(pc_i[24]),
    .Y(_208_)
  );
  NOR _408_ (
    .A(pc_i[27]),
    .B(pc_i[26]),
    .Y(_209_)
  );
  NAND _409_ (
    .A(_208_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _410_ (
    .A(_207_),
    .B(_210_),
    .Y(_211_)
  );
  NAND _411_ (
    .A(_204_),
    .B(_211_),
    .Y(_212_)
  );
  NOT _412_ (
    .A(_212_),
    .Y(_213_)
  );
  NAND _413_ (
    .A(pc_i[5]),
    .B(pc_i[4]),
    .Y(_214_)
  );
  NAND _414_ (
    .A(pc_i[7]),
    .B(pc_i[6]),
    .Y(_215_)
  );
  NOR _415_ (
    .A(_214_),
    .B(_215_),
    .Y(_216_)
  );
  NAND _416_ (
    .A(_069_),
    .B(pc_i[3]),
    .Y(_217_)
  );
  NOR _417_ (
    .A(pc_i[1]),
    .B(pc_i[0]),
    .Y(_218_)
  );
  NOT _418_ (
    .A(_218_),
    .Y(_219_)
  );
  NOR _419_ (
    .A(_217_),
    .B(_219_),
    .Y(_220_)
  );
  NAND _420_ (
    .A(_216_),
    .B(_220_),
    .Y(_221_)
  );
  NOR _421_ (
    .A(pc_i[15]),
    .B(pc_i[14]),
    .Y(_222_)
  );
  NOR _422_ (
    .A(pc_i[13]),
    .B(pc_i[12]),
    .Y(_223_)
  );
  NAND _423_ (
    .A(_222_),
    .B(_223_),
    .Y(_224_)
  );
  NOR _424_ (
    .A(pc_i[9]),
    .B(pc_i[8]),
    .Y(_225_)
  );
  NOR _425_ (
    .A(pc_i[11]),
    .B(pc_i[10]),
    .Y(_226_)
  );
  NAND _426_ (
    .A(_225_),
    .B(_226_),
    .Y(_227_)
  );
  NOR _427_ (
    .A(_224_),
    .B(_227_),
    .Y(_228_)
  );
  NOT _428_ (
    .A(_228_),
    .Y(_229_)
  );
  NOR _429_ (
    .A(_221_),
    .B(_229_),
    .Y(_230_)
  );
  NAND _430_ (
    .A(_213_),
    .B(_230_),
    .Y(_231_)
  );
  NAND _431_ (
    .A(_066_),
    .B(_231_),
    .Y(_033_)
  );
  NOT _432_ (
    .A(start_i),
    .Y(_001_)
  );
  NOT _433_ (
    .A(start_i),
    .Y(_002_)
  );
  NOT _434_ (
    .A(start_i),
    .Y(_003_)
  );
  NOT _435_ (
    .A(start_i),
    .Y(_004_)
  );
  NOT _436_ (
    .A(start_i),
    .Y(_005_)
  );
  NOT _437_ (
    .A(start_i),
    .Y(_006_)
  );
  NOT _438_ (
    .A(start_i),
    .Y(_007_)
  );
  NOT _439_ (
    .A(start_i),
    .Y(_008_)
  );
  NOT _440_ (
    .A(start_i),
    .Y(_009_)
  );
  NOT _441_ (
    .A(start_i),
    .Y(_010_)
  );
  NOT _442_ (
    .A(start_i),
    .Y(_011_)
  );
  NOT _443_ (
    .A(start_i),
    .Y(_012_)
  );
  NOT _444_ (
    .A(start_i),
    .Y(_013_)
  );
  NOT _445_ (
    .A(start_i),
    .Y(_014_)
  );
  NOT _446_ (
    .A(start_i),
    .Y(_015_)
  );
  NOT _447_ (
    .A(start_i),
    .Y(_016_)
  );
  NOT _448_ (
    .A(start_i),
    .Y(_017_)
  );
  NOT _449_ (
    .A(start_i),
    .Y(_018_)
  );
  NOT _450_ (
    .A(start_i),
    .Y(_019_)
  );
  NOT _451_ (
    .A(start_i),
    .Y(_020_)
  );
  NOT _452_ (
    .A(start_i),
    .Y(_021_)
  );
  NOT _453_ (
    .A(start_i),
    .Y(_022_)
  );
  NOT _454_ (
    .A(start_i),
    .Y(_023_)
  );
  NOT _455_ (
    .A(start_i),
    .Y(_024_)
  );
  NOT _456_ (
    .A(start_i),
    .Y(_025_)
  );
  NOT _457_ (
    .A(start_i),
    .Y(_026_)
  );
  NOT _458_ (
    .A(start_i),
    .Y(_027_)
  );
  NOT _459_ (
    .A(start_i),
    .Y(_028_)
  );
  NOT _460_ (
    .A(start_i),
    .Y(_029_)
  );
  NOT _461_ (
    .A(start_i),
    .Y(_030_)
  );
  NOT _462_ (
    .A(start_i),
    .Y(_031_)
  );
  NOT _463_ (
    .A(start_i),
    .Y(_032_)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _464_ (
    .C(clk_i),
    .D(_033_),
    .Q(flag),
    .R(_000_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _465_ (
    .C(clk_i),
    .D(_034_),
    .Q(pc_o[0]),
    .R(_001_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _466_ (
    .C(clk_i),
    .D(_035_),
    .Q(pc_o[1]),
    .R(_002_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _467_ (
    .C(clk_i),
    .D(_036_),
    .Q(pc_o[2]),
    .R(_003_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _468_ (
    .C(clk_i),
    .D(_037_),
    .Q(pc_o[3]),
    .R(_004_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _469_ (
    .C(clk_i),
    .D(_038_),
    .Q(pc_o[4]),
    .R(_005_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _470_ (
    .C(clk_i),
    .D(_039_),
    .Q(pc_o[5]),
    .R(_006_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _471_ (
    .C(clk_i),
    .D(_040_),
    .Q(pc_o[6]),
    .R(_007_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _472_ (
    .C(clk_i),
    .D(_041_),
    .Q(pc_o[7]),
    .R(_008_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _473_ (
    .C(clk_i),
    .D(_042_),
    .Q(pc_o[8]),
    .R(_009_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _474_ (
    .C(clk_i),
    .D(_043_),
    .Q(pc_o[9]),
    .R(_010_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _475_ (
    .C(clk_i),
    .D(_044_),
    .Q(pc_o[10]),
    .R(_011_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _476_ (
    .C(clk_i),
    .D(_045_),
    .Q(pc_o[11]),
    .R(_012_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _477_ (
    .C(clk_i),
    .D(_046_),
    .Q(pc_o[12]),
    .R(_013_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _478_ (
    .C(clk_i),
    .D(_047_),
    .Q(pc_o[13]),
    .R(_014_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _479_ (
    .C(clk_i),
    .D(_048_),
    .Q(pc_o[14]),
    .R(_015_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _480_ (
    .C(clk_i),
    .D(_049_),
    .Q(pc_o[15]),
    .R(_016_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _481_ (
    .C(clk_i),
    .D(_050_),
    .Q(pc_o[16]),
    .R(_017_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _482_ (
    .C(clk_i),
    .D(_051_),
    .Q(pc_o[17]),
    .R(_018_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _483_ (
    .C(clk_i),
    .D(_052_),
    .Q(pc_o[18]),
    .R(_019_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _484_ (
    .C(clk_i),
    .D(_053_),
    .Q(pc_o[19]),
    .R(_020_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _485_ (
    .C(clk_i),
    .D(_054_),
    .Q(pc_o[20]),
    .R(_021_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _486_ (
    .C(clk_i),
    .D(_055_),
    .Q(pc_o[21]),
    .R(_022_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _487_ (
    .C(clk_i),
    .D(_056_),
    .Q(pc_o[22]),
    .R(_023_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _488_ (
    .C(clk_i),
    .D(_057_),
    .Q(pc_o[23]),
    .R(_024_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _489_ (
    .C(clk_i),
    .D(_058_),
    .Q(pc_o[24]),
    .R(_025_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _490_ (
    .C(clk_i),
    .D(_059_),
    .Q(pc_o[25]),
    .R(_026_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _491_ (
    .C(clk_i),
    .D(_060_),
    .Q(pc_o[26]),
    .R(_027_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _492_ (
    .C(clk_i),
    .D(_061_),
    .Q(pc_o[27]),
    .R(_028_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _493_ (
    .C(clk_i),
    .D(_062_),
    .Q(pc_o[28]),
    .R(_029_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _494_ (
    .C(clk_i),
    .D(_063_),
    .Q(pc_o[29]),
    .R(_030_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _495_ (
    .C(clk_i),
    .D(_064_),
    .Q(pc_o[30]),
    .R(_031_),
    .S(1'h0)
  );
  (* src = "D:\\SoftwareFrameWork\\RISCVProcessor\\PC.v:46.1-58.4" *)
  DFFSR _496_ (
    .C(clk_i),
    .D(_065_),
    .Q(pc_o[31]),
    .R(_032_),
    .S(1'h0)
  );
endmodule
